replaced init script

diff --git a/files/jmeter-server b/files/jmeter-server
--- a/files/jmeter-server
+++ b/files/jmeter-server
@@ -1,60 +1,133 @@
 #!/bin/sh
 ### BEGIN INIT INFO
 # Provides:          jmeter-server
-# Required-Start:    $all
-# Required-Stop:     $all
+# Required-Start:    $syslog $local_fs
+# Required-Stop:     $syslog $local_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: starts the jmeter server
-# Description:       starts the jmeter server
+# Short-Description: Apache JMeter Remote Server
+# Description:       Apache JMeter Remote Server runs JMeter tests issued from a remote server.
 ### END INIT INFO
-#
-#  Once installed, use "sudo update-rc.d jmeter-server defaults" to enable!
 
-# Source function library
+# Author: Steve Kamerman <steve at scientiamobile dot com>
+
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin
+DESC="Apache JMeter Remote Server"
+NAME=jmeter-server
+JMETER_PATH=/usr/share/jmeter
+# Change this to your IP
+JMETER_IP=33.33.33.40
+JMETER_PORT=1099
+DAEMON="$JMETER_PATH/bin/$NAME"
+DAEMON_ARGS="-Djava.rmi.server.hostname=$JMETER_IP -Dserver_port=$JMETER_PORT -s -j $JMETER_PATH/bin/jmeter-server.log"
+PIDFILE=/var/run/$NAME.pid
+SCRIPTNAME=/etc/init.d/$NAME
+
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
+
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
 . /lib/lsb/init-functions
 
-NAME=jmeter-server
-DESC="jmeter server"
-DAEMON=/usr/share/jmeter/bin/jmeter-server
-PIDFILE=/var/run/$NAME.pid
-DAEMON_OPTS=""
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+        # Return
+        #   0 if daemon has been started
+        #   1 if daemon was already running
+        #   2 if daemon could not be started
+        start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+                || return 1
+        start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- \
+                $DAEMON_ARGS \
+                || return 2
+        # Add code here, if necessary, that waits for the process to be ready
+        # to handle requests from services started subsequently which depend
+        # on this one.  As a last resort, sleep for some time.
+}
 
-test -x /usr/bin/java || exit 0
-test -x $DAEMON || exit 0
-
-set -e
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+        # Return
+        #   0 if daemon has been stopped
+        #   1 if daemon was already stopped
+        #   2 if daemon could not be stopped
+        #   other if a failure occurred
+        start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
+        RETVAL="$?"
+        [ "$RETVAL" = 2 ] && return 2
+        # Wait for children to finish too if this is a daemon that forks
+        # and if the daemon is only ever run from this initscript.
+        # If the above conditions are not satisfied then add some other code
+        # that waits for the process to drop all resources that could be
+        # needed by services started subsequently.  A last resort is to
+        # sleep for some time.
+        start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+        [ "$?" = 2 ] && return 2
+        # Many daemons don't delete their pidfiles when they exit.
+        rm -f $PIDFILE
+        return "$RETVAL"
+}
 
 case "$1" in
   start)
-    echo "Starting $DESC"
-    if start-stop-daemon \
-      --start --background --quiet --pidfile ${PIDFILE} --exec ${DAEMON} -- \
-      ${DAEMON_OPTS} 2>&1; then
-      echo "$DESC started"
-      exit 0
-    else
-      cat $output
-      exit 1
-    fi
-    ;;
+        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+        do_start
+        case "$?" in
+                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+        esac
+        ;;
   stop)
-    echo "Stopping $DESC"
-    if ps fauwx | grep org.apache.jmeter.NewDriver | grep -v vi | grep -v grep | awk {'print $2'} | xargs kill; then
-       echo "$DESC stopped"
-      exit 0
-    else
-      exit 1
-    fi
-    ;;
-  restart)
-    $0 stop
-    $0 start
-    ;;
+        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+        do_stop
+        case "$?" in
+                0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+                2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+        esac
+        ;;
+  status)
+       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+       ;;
+  restart|force-reload)
+        #
+        # If the "reload" option is implemented then remove the
+        # 'force-reload' alias
+        #
+        log_daemon_msg "Restarting $DESC" "$NAME"
+        do_stop
+        case "$?" in
+          0|1)
+                do_start
+                case "$?" in
+                        0) log_end_msg 0 ;;
+                        1) log_end_msg 1 ;; # Old process is still running
+                        *) log_end_msg 1 ;; # Failed to start
+                esac
+                ;;
+          *)
+                # Failed to stop
+                log_end_msg 1
+                ;;
+        esac
+        ;;
   *)
-    echo "Usage: $0 {start|stop|restart}"
-    exit 1
-    ;;
+        echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+        exit 3
+        ;;
 esac
 
-exit 0
+:
